core/urls.py
from django.urls import path, include
from . import views

from core import views
app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    # path('', views.home, name='home'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('product/', views.product, name='product'),
    path('product/<slug>/', views.ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('order-summary/', views.OrderSummaryView.as_view(), name='order-summary'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    # path('payment', views.PaymentView, name='payment'),
    path('payment/<payment_method>', views.PaymentView.as_view(), name='payment'),
    path('paypal-return/', views.paypal_return, name='paypal-return'),
    path('paypal-cancel/', views.paypal_cancel, name='paypal-cancel'),
    path('checkout-v2/', views.CheckoutViewV2.as_view(), name='checkout-v2'),
]

ecomm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('paypal/', include('paypal.standard.ipn.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField

CATETORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'Paypal')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping')
)

class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATETORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()

    def __self__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            "slug": self.slug
        })
    
    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            "slug": self.slug
        })
    
    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            "slug": self.slug
        })
    
    class Meta:
        verbose_name_plural = 'Item'

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __self__(self):
        return f"{self.quantity} of {self.item.title}"
    
    def get_total_harga_item(self):
        return self.quantity * self.item.price
    
    def get_total_discount_item(self):
        return self.quantity * self.item.discount_price
    
    def get_total_hemat_item(self):
        return self.get_total_harga_item() - self.get_total_discount_item()

    def get_total_item_keseluruan(self):
        if self.item.discount_price:
            return self.get_total_discount_item()
        return self.get_total_harga_item()
    
    def get_total_hemat_keseluruhan(self):
        if self.item.discount_price:
            return self.get_total_hemat_item()
        return 0
    
    class Meta:
        verbose_name_plural = 'OrderItem'

class Order(models.Model):
    trasaction_id = models.CharField(max_length=500, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateField(auto_now_add=True)
    ordered_date = models.DateField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    shipping_address = models.ForeignKey('Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)

    def __self__(self):
        return self.user.username
    
    def get_total_harga_order(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_item_keseluruan()
        return total
    
    def get_total_hemat_order(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_hemat_keseluruhan()
        return total
    class Meta:
        verbose_name_plural = 'Order'
    
class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    alamat_lokasi = models.CharField(max_length=100)
    alamat_apartemen = models.CharField(max_length=100)
    negara = CountryField(multiple=False)
    kode_pos = models.CharField(max_length=20)
    tipe_alamat = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __self__(self):
        return self.user.username
    
class Payment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)
    payment_option = models.CharField(choices=PAYMENT_CHOICES, max_length=1)
    charge_id = models.CharField(max_length=50)

    def __self__(self):
        return self.user.username
    
    class Meta:
        verbose_name_plural = 'Payment'

core/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

class ContactForm(forms.Form):
    nama = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Nama Anda'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Email Anda'}))
    pesan = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Pesan Anda'}))


class AddressForm(forms.Form):
    pass

PILIHAN_PEMBAYARAN = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)

class CheckoutForm(forms.Form):
    alamat_lokasi = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Alamat Anda', 'class': 'textinput form-control'}))
    alamat_apartemen = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Apartement, Rumah, atau yang lain (opsional)', 'class': 'textinput form-control'}))
    negara = CountryField(blank_label='(Pilih Negara)').formfield(widget=CountrySelectWidget(attrs={'class': 'countryselectwidget form-select'}))
    kode_pos = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Kode Pos', 'class': 'form-control'}))
    alamat_penagihan_sama = forms.BooleanField(widget=forms.CheckboxInput(), required=False)
    simpan_info_alamat = forms.BooleanField(widget=forms.CheckboxInput(), required=False)
    opsi_pembayaran = forms.ChoiceField(widget=forms.RadioSelect(), choices=PILIHAN_PEMBAYARAN)


class CheckoutFormV2(forms.Form):
    alamat_pengiriman = forms.CharField(required=False)
    alamat_pengiriman2 = forms.CharField(required=False)
    negara_pengiriman = CountryField(blank_label='(pilih negara)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'countryselectwidget form-select',
        }))
    kodepos_pengiriman = forms.CharField(required=False)

    alamat_penagihan = forms.CharField(required=False)
    alamat_penagihan2 = forms.CharField(required=False)
    negara_penagihan = CountryField(blank_label='(pilih negara)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'countryselectwidget form-select',
        }))
    kodepos_penagihan = forms.CharField(required=False)

    sama_alamat_penagihan = forms.BooleanField(required=False)
    set_default_pengiriman = forms.BooleanField(required=False)
    use_default_pengiriman = forms.BooleanField(required=False)
    set_default_penagihan = forms.BooleanField(required=False)
    use_default_penagihan = forms.BooleanField(required=False)

    opsi_pembayaran = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PILIHAN_PEMBAYARAN)

ecomm/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>

    <title>e-commerce {% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    
    <!-- MDB icon -->
    <link rel="icon" href="{% static 'img/mdb-favicon.ico' %}" type="image/x-icon" />
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    />
    <!-- Google Fonts Roboto -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
    />
    <!-- MDB -->
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
  </head>
  <body>
    
    {% include 'navbar.html' %}
 

    <div class="mt-5 pt-4">
      {% if messages %}
          {% for message in messages %}
          <div class="container">
            <div class="alert alert-{{ message.tags }} alert-dismissable">
              <strong>{{ message }}</strong>
            </div>
          </div>
          {% endfor %}
      {% endif %}
    </div>

    {% block content %}
    {% endblock content %}
    
    {% include 'footer.html' %}
  
    {% include 'scripts.html' %}

    {% block scripts %}
    {% endblock scripts %}

  </body>
</html>

ecomm/templates/carousel.html
<!-- carousel -->
<div id="carouselExampleCaptions" class="carousel slide carousel-fade" data-mdb-ride="carousel">
    <div class="carousel-indicators">
        <button
                type="button"
                data-mdb-target="#carouselExampleCaptions"
                data-mdb-slide-to="0"
                class="active"
                aria-current="true"
                aria-label="Slide 1"
        ></button>
        <button
                type="button"
                data-mdb-target="#carouselExampleCaptions"
                data-mdb-slide-to="1"
                aria-label="Slide 2"
        ></button>
        <button
                type="button"
                data-mdb-target="#carouselExampleCaptions"
                data-mdb-slide-to="2"
                aria-label="Slide 3"
        ></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg" class="d-block w-100" alt="Wild Landscape"/>
            <div class="mask" style="background-color: rgba(0, 0, 0, 0.4)"></div>
            <div class="carousel-caption d-none d-sm-block mb-5">
                <h1 class="mb-4">
                    <strong>Nikmati kemudahan berbelanja di Toko kami</strong>
                </h1>

                <p>
                    <strong>Temukan Gaya Anda dengan Kemudahan Belanja Online di Toko Kami - Fashion Berkualitas Tinggi Hanya di Sini!/strong>
                </p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg" class="d-block w-100" alt="Camera"/>
            <div class="mask" style="background-color: rgba(0, 0, 0, 0.4)"></div>
            <div class="carousel-caption d-none d-md-block mb-5">
                <h1 class="mb-4">
                    <strong>Nikmati kemudahan berbelanja di Toko kami</strong>
                </h1>
                <p>
                    <strong>Temukan Gaya Anda dengan Kemudahan Belanja Online di Toko Kami - Fashion Berkualitas Tinggi Hanya di Sini!</strong>
                </p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg" class="d-block w-100" alt="Exotic Fruits"/>
            <div class="mask" style="background-color: rgba(0, 0, 0, 0.4)"></div>
            <div class="carousel-caption d-none d-md-block mb-5">
                <h1 class="mb-4">
                    <strong>Nikmati kemudahan berbelanja di Toko kami</strong>
                </h1>

                <p>
                    <strong>Temukan Gaya Anda dengan Kemudahan Belanja Online di Toko Kami - Fashion Berkualitas Tinggi Hanya di Sini!</strong>
                </p>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-mdb-target="#carouselExampleCaptions" data-mdb-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-mdb-target="#carouselExampleCaptions" data-mdb-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

ecomm/templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<!--Main layout-->
<main>
    <form method="POST" name="formCheckout">
        {% csrf_token %}
        <div class="container">
            <!-- Heading -->
            <h2 class="my-5 text-center">Checkout</h2>

            <!--Grid row-->
            <div class="row">
                    <!--Grid column-->
                    <div class="col-md-8 mb-4">
                        <!--Card-->
                        <div class="card p-4">
                            <!--address-->
                            <p class="mb-0">
                                Alamat
                            </p>
                            <div class="form-outline mb-4">
                                {{ form.alamat_lokasi }}
                            </div>

                            <!--address-2-->
                            <p class="mb-0">
                                Alamat 2 (optional)
                            </p>
                            <div class="form-outline mb-4">
                                {{ form.alamat_apartemen }}
                            </div>

                            <!--Grid row-->
                            <div class="row">
                                <!--Grid column-->
                                <div class="col-lg-4 col-md-12 mb-4">
                                    <p class="mb-0">
                                        Negara
                                    </p>
                                    <div class="form-outline mb-4">
                                        {{ form.negara }}
                                    </div>
                                </div>
                                <!--Grid column-->

                                <!--Grid column-->
                                <div class="col-lg-4 col-md-12 mb-4">
                                    <p class="mb-0">
                                        Kode Pos*
                                    </p>
                                    {{ form.kode_pos }}
                                </div>
                                <!--Grid column-->
                            </div>
                            <!--Grid row-->

                            <hr />
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="" id="id_alamat_penagihan_sama" name="alamat_penagihan_sama"
                                {% if form.alamat_penagihan_sama.value %}checked{% endif %}
                                />
                            <label class="form-check-label" for="id_alamat_penagihan_sama">Alamat pengiriman sama dengan alamat tagihan saya.</label>
                                
                            </div>

                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="" id="id_simpan_info_alamat" name="simpan_info_alamat"
                                {% if form.simpan_info_alamat.value %}checked{% endif %}
                                />
                                <label class="form-check-label" for="id_simpan_info_alamat">Simpan informasi ini untuk penggunaan selanjutnya.</label>
                            </div>

                            <hr />

                            <div class="my-3">
                                {% for value, name in form.fields.opsi_pembayaran.choices %}
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="opsi_pembayaran" id="{{ name }}" value="{{ value }}" required />
                                    <label class="form-check-label" for="{{ name }}">{{ name }}</label>
                                </div>
                                {% endfor %}
                            </div>
                            
                            <hr class="mb-4" />
                            <button class="btn btn-primary" type="submit" name="btnCheckout" {% if order.get_total_harga_order <= 0 %}disabled{% endif %}>Lanjut Checkout</button>
                        </div>
                        <!--/.Card-->
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-4 mb-4">
                        <!-- Heading -->
                        <h4 class="d-flex justify-content-between align-items-center mb-3">
                            <span class="text-muted">Keranjang kamu</span>
                            <span class="badge rounded-pill badge-primary">{{ order.items.all.count }}</span>
                        </h4>

                        <!-- Cart -->
                        <ul class="list-group mb-3">
                            {% for belanjaan in order.items.all%}
                            <li class="list-group-item d-flex justify-content-between">

                                <div>
                                    <h6 class="my-0">{{ belanjaan.quantity }} x {{ belanjaan.item.title }}</h6>
                                    <small class="text-muted">{{ belanjaan.item.description|truncatechars:95 }}</small>
                                </div>

                                {% if belanjaan.item.discount_price %}
                                <span class="text-muted">${{ belanjaan.get_total_discount_item }}
                                {% else %}
                                ${{ belanjaan.get_total_harga_item}}
                                {% endif %}

                            </li>
                            {% endfor %}
                            <li class="list-group-item d-flex justify-content-between">
                                <span>Total belajaan</span>
                                <strong class="text-success">${{ order.get_total_harga_order }}</strong>
                            </li>
                        </ul>
                        <!-- Cart -->
                    </div>
                    <!--Grid column-->
            
            </div>
            <!--Grid row-->
        </div>
    </form>
</main>
<!--Main layout-->

{% endblock content %}

ecomm/templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}Kontak kami{% endblock %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-7">
                <h2 class="h3 mb-3 text-black">Tuliskan pesan Anda</h2>
            </div>
            <div class="col-md-7">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-primary btn-lg btn-block" value="Submit message" />
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

ecomm/templates/index.html
{% extends 'base.html' %}

{% block content %}

{% include 'carousel.html' %}

<!--Main layout-->
<main>
    <div class="container">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark mt-3 mb-5 shadow p-2" style="background-color: #607D8B">
            <!-- Container wrapper -->
            <div class="container-fluid">

                <!-- Navbar brand -->
                <a class="navbar-brand" href="#">Categories:</a>

                <!-- Toggle button -->
                <button
                        class="navbar-toggler"
                        type="button"
                        data-mdb-toggle="collapse"
                        data-mdb-target="#navbarSupportedContent2"
                        aria-controls="navbarSupportedContent2"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>

                <!-- Collapsible wrapper -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent2">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                        <!-- Link -->
                        <li class="nav-item acitve">
                            <a class="nav-link text-white" href="#">All</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="#">Shirts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="#">Sport wears</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="#">Outwears</a>
                        </li>

                    </ul>

                    <!-- Search -->
                    <form class="w-auto py-1" style="max-width: 12rem">
                        <input type="search" class="form-control rounded-0" placeholder="Search" aria-label="Search">
                    </form>

                </div>
            </div>
            <!-- Container wrapper -->
        </nav>
        <!-- Navbar -->

        <!-- Products -->
        <section>
            <div class="text-center">
                <div class="row">
                    {% for item in object_list %}
                    <div class="col-lg-3 col-md-6 mb-4">
                        <div class="card">
                            <div class="bg-image hover-zoom ripple ripple-surface ripple-surface-light"
                                 data-mdb-ripple-color="light">
                                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
                                     class="w-100" />
                                <a href="{{ item.get_absolute_url }}">
                                    <div class="mask">
                                        <div class="d-flex justify-content-start align-items-end h-100">
                                            <h5><span class="badge bg-dark ms-2">NEW</span></h5>
                                        </div>
                                    </div>
                                    <div class="hover-overlay">
                                        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                                    </div>
                                </a>
                            </div>
                            <div class="card-body">
                                <a href="{{ item.get_absolute_url }}" class="text-reset">
                                    <h5 class="card-title mb-2">{{ item.title }}</h5>
                                </a>
                                <a href="" class="text-reset ">
                                    <p>{{ item.get_category_display }}</p>
                                </a>
                                <h6 class="mb-3 price">${% if item.discount_price %}{{ item.discount_price }}{% else %}{{ item.price }}{% endif %}
                                </h6>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>

        <!-- Pagination -->
        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-3">
            <ul class="pagination">
                <li class="page-item disabled">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">4</a></li>
                <li class="page-item"><a class="page-link" href="#">5</a></li>
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- Pagination -->
    </div>
</main>
<!--Main layout-->
{% endblock content %}

ecomm/templates/keranjang.html
<!--Grid column-->
<div class="col-md-4 mb-4">
    <!-- Heading -->
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Keranjang kamu</span>
        <span class="badge rounded-pill badge-primary">{{ order.items.all.count }}</span>
    </h4>

    <!-- Cart -->
    <ul class="list-group mb-3">
        {% for belanjaan in order.items.all%}
        <li class="list-group-item d-flex justify-content-between">

            <div>
                <h6 class="my-0">{{ belanjaan.quantity }} x {{ belanjaan.item.title }}</h6>
                <small class="text-muted">{{ belanjaan.item.description|truncatechars:95 }}</small>
            </div>

            {% if belanjaan.item.discount_price %}
            <span class="text-muted">${{ belanjaan.get_total_discount_item }}
            {% else %}
            ${{ belanjaan.get_total_harga_item}}
            {% endif %}

        </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between">
            <span>Total belajaan</span>
            <strong class="text-success">${{ order.get_total_harga_order }}</strong>
        </li>
    </ul>
    <!-- Cart -->
</div>
<!--Grid column-->

ecomm/templates/product.html
{% extends 'base.html' %}

{% block content %}

<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container mt-5">
        <!--Grid row-->
        <div class="row">
            <!--Grid column-->
            <div class="col-md-6 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-6 mb-4">
                <!--Content-->
                <div class="p-4">
                    <div class="mb-3">
                        <a href="">
                            <span class="badge bg-dark me-1">{{ object.get_category_display }}</span>
                        </a>
                        <a href="">
                            <span class="badge bg-info me-1">New</span>
                        </a>
                        <a href="">
                            <span class="badge bg-danger me-1">Bestseller</span>
                        </a>
                    </div>

                    <p class="lead">
                        {% if object.discount_price %}
                        <span class="me-1">
                            <del>${{ object.price }}</del>
                        </span>
                        <span>${{ object.discount_price }}</span>
                        {% else %}
                        <span>${{ object.price }}</span>
                        {% endif %}
                    </p>

                    <strong><p style="font-size: 20px;">Description</p></strong>

                    <p>{{ object.description }}</p>

                    {% comment %} <div class="d-flex justify-content-left">
                        <div class="form-outline me-1 mb-3" style="width: 100px;">
                            Total: <strong>{{ object.items.quantity }}</strong>
                        </div>
                    </div> {% endcomment %}

                    <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary ms-1">
                        Add to cart
                        <i class="fas fa-shopping-cart ms-1"></i>
                    </a>

                    <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger ms-1">
                        Remove from cart
                        <i class="fas fa-shopping-cart ms-1"></i>
                    </a>
                </div>
                <!--Content-->
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->

        <hr />

        <!--Grid row-->
        <div class="row d-flex justify-content-center">
            <!--Grid column-->
            <div class="col-md-6 text-center">
                <h4 class="my-4 h4">Additional information</h4>

                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit voluptates, quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->

        <!--Grid row-->
        <div class="row">
            <!--Grid column-->
            <div class="col-lg-4 col-md-12 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->
    </div>
</main>
<!--Main layout-->

{% endblock content %}